import './globals.css';
import RootLayoutClient from './client-layout';

export const metadata = {
  title: "My App",
  description: "Generated by Next.js + Clerk",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-gray-100 dark:bg-gray-900">
        <RootLayoutClient>
          {children}
        </RootLayoutClient>
      </body>
    </html>
  );
}